/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnimationData {
  'id' : string,
  'characterCustomization' : CharacterCustomization,
  'animationBlob' : ExternalBlob,
  'backgroundAudioBlob' : ExternalBlob,
  'createdAt' : Time,
  'videoBlob' : ExternalBlob,
  'narrationAudioBlob' : ExternalBlob,
  'sceneCustomization' : SceneCustomization,
  'audioSettings' : AudioSettings,
  'modelBlob' : ExternalBlob,
  'prompt' : string,
  'isAIGenerated' : boolean,
  'textureBlob' : ExternalBlob,
}
export interface AudioSettings {
  'soundEffectsVolume' : bigint,
  'includeSoundEffects' : boolean,
  'narrationVolume' : bigint,
  'includeNarration' : boolean,
}
export interface CharacterCustomization {
  'accessories' : Array<string>,
  'characterType' : CharacterType,
  'color' : string,
  'props' : Array<string>,
  'emotionalTone' : EmotionalTone,
}
export type CharacterType = { 'human' : null } |
  { 'animal' : null } |
  { 'fantasyCreature' : null };
export type EmotionalTone = { 'sad' : null } |
  { 'surprised' : null } |
  { 'happy' : null } |
  { 'excited' : null };
export type Environment = { 'city' : null } |
  { 'desert' : null } |
  { 'space' : null } |
  { 'underwater' : null } |
  { 'forest' : null };
export type ExternalBlob = Uint8Array;
export interface SceneCustomization {
  'backgroundElements' : Array<string>,
  'environment' : Environment,
}
export type Time = bigint;
export interface UserPreferences {
  'favoriteEnvironments' : Array<Environment>,
  'preferredEmotionalTone' : EmotionalTone,
  'preferredColors' : Array<string>,
  'defaultAudioSettings' : AudioSettings,
  'favoriteCharacterTypes' : Array<CharacterType>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'downloadVideo' : ActorMethod<[ExternalBlob], undefined>,
  'generateAIAnimation' : ActorMethod<
    [
      string,
      EmotionalTone,
      AudioSettings,
      ExternalBlob,
      ExternalBlob,
      ExternalBlob,
      ExternalBlob,
      ExternalBlob,
      ExternalBlob,
    ],
    AnimationData
  >,
  'getAIGeneratedAnimations' : ActorMethod<[], Array<AnimationData>>,
  'getAllAnimations' : ActorMethod<[], Array<AnimationData>>,
  'getAnimation' : ActorMethod<[string], AnimationData>,
  'getUserPreferences' : ActorMethod<[], UserPreferences>,
  'isAIGenerated' : ActorMethod<[string], boolean>,
  'setUserPreferences' : ActorMethod<[UserPreferences], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];