/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const EmotionalTone = IDL.Variant({
  'sad' : IDL.Null,
  'surprised' : IDL.Null,
  'happy' : IDL.Null,
  'excited' : IDL.Null,
});
export const AudioSettings = IDL.Record({
  'soundEffectsVolume' : IDL.Int,
  'includeSoundEffects' : IDL.Bool,
  'narrationVolume' : IDL.Int,
  'includeNarration' : IDL.Bool,
});
export const CharacterType = IDL.Variant({
  'human' : IDL.Null,
  'animal' : IDL.Null,
  'fantasyCreature' : IDL.Null,
});
export const CharacterCustomization = IDL.Record({
  'accessories' : IDL.Vec(IDL.Text),
  'characterType' : CharacterType,
  'color' : IDL.Text,
  'props' : IDL.Vec(IDL.Text),
  'emotionalTone' : EmotionalTone,
});
export const Time = IDL.Int;
export const Environment = IDL.Variant({
  'city' : IDL.Null,
  'desert' : IDL.Null,
  'space' : IDL.Null,
  'underwater' : IDL.Null,
  'forest' : IDL.Null,
});
export const SceneCustomization = IDL.Record({
  'backgroundElements' : IDL.Vec(IDL.Text),
  'environment' : Environment,
});
export const AnimationData = IDL.Record({
  'id' : IDL.Text,
  'characterCustomization' : CharacterCustomization,
  'animationBlob' : ExternalBlob,
  'backgroundAudioBlob' : ExternalBlob,
  'createdAt' : Time,
  'videoBlob' : ExternalBlob,
  'narrationAudioBlob' : ExternalBlob,
  'sceneCustomization' : SceneCustomization,
  'audioSettings' : AudioSettings,
  'modelBlob' : ExternalBlob,
  'prompt' : IDL.Text,
  'isAIGenerated' : IDL.Bool,
  'textureBlob' : ExternalBlob,
});
export const UserPreferences = IDL.Record({
  'favoriteEnvironments' : IDL.Vec(Environment),
  'preferredEmotionalTone' : EmotionalTone,
  'preferredColors' : IDL.Vec(IDL.Text),
  'defaultAudioSettings' : AudioSettings,
  'favoriteCharacterTypes' : IDL.Vec(CharacterType),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'downloadVideo' : IDL.Func([ExternalBlob], [], ['query']),
  'generateAIAnimation' : IDL.Func(
      [
        IDL.Text,
        EmotionalTone,
        AudioSettings,
        ExternalBlob,
        ExternalBlob,
        ExternalBlob,
        ExternalBlob,
        ExternalBlob,
        ExternalBlob,
      ],
      [AnimationData],
      [],
    ),
  'getAIGeneratedAnimations' : IDL.Func(
      [],
      [IDL.Vec(AnimationData)],
      ['query'],
    ),
  'getAllAnimations' : IDL.Func([], [IDL.Vec(AnimationData)], ['query']),
  'getAnimation' : IDL.Func([IDL.Text], [AnimationData], ['query']),
  'getUserPreferences' : IDL.Func([], [UserPreferences], ['query']),
  'isAIGenerated' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'setUserPreferences' : IDL.Func([UserPreferences], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const EmotionalTone = IDL.Variant({
    'sad' : IDL.Null,
    'surprised' : IDL.Null,
    'happy' : IDL.Null,
    'excited' : IDL.Null,
  });
  const AudioSettings = IDL.Record({
    'soundEffectsVolume' : IDL.Int,
    'includeSoundEffects' : IDL.Bool,
    'narrationVolume' : IDL.Int,
    'includeNarration' : IDL.Bool,
  });
  const CharacterType = IDL.Variant({
    'human' : IDL.Null,
    'animal' : IDL.Null,
    'fantasyCreature' : IDL.Null,
  });
  const CharacterCustomization = IDL.Record({
    'accessories' : IDL.Vec(IDL.Text),
    'characterType' : CharacterType,
    'color' : IDL.Text,
    'props' : IDL.Vec(IDL.Text),
    'emotionalTone' : EmotionalTone,
  });
  const Time = IDL.Int;
  const Environment = IDL.Variant({
    'city' : IDL.Null,
    'desert' : IDL.Null,
    'space' : IDL.Null,
    'underwater' : IDL.Null,
    'forest' : IDL.Null,
  });
  const SceneCustomization = IDL.Record({
    'backgroundElements' : IDL.Vec(IDL.Text),
    'environment' : Environment,
  });
  const AnimationData = IDL.Record({
    'id' : IDL.Text,
    'characterCustomization' : CharacterCustomization,
    'animationBlob' : ExternalBlob,
    'backgroundAudioBlob' : ExternalBlob,
    'createdAt' : Time,
    'videoBlob' : ExternalBlob,
    'narrationAudioBlob' : ExternalBlob,
    'sceneCustomization' : SceneCustomization,
    'audioSettings' : AudioSettings,
    'modelBlob' : ExternalBlob,
    'prompt' : IDL.Text,
    'isAIGenerated' : IDL.Bool,
    'textureBlob' : ExternalBlob,
  });
  const UserPreferences = IDL.Record({
    'favoriteEnvironments' : IDL.Vec(Environment),
    'preferredEmotionalTone' : EmotionalTone,
    'preferredColors' : IDL.Vec(IDL.Text),
    'defaultAudioSettings' : AudioSettings,
    'favoriteCharacterTypes' : IDL.Vec(CharacterType),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'downloadVideo' : IDL.Func([ExternalBlob], [], ['query']),
    'generateAIAnimation' : IDL.Func(
        [
          IDL.Text,
          EmotionalTone,
          AudioSettings,
          ExternalBlob,
          ExternalBlob,
          ExternalBlob,
          ExternalBlob,
          ExternalBlob,
          ExternalBlob,
        ],
        [AnimationData],
        [],
      ),
    'getAIGeneratedAnimations' : IDL.Func(
        [],
        [IDL.Vec(AnimationData)],
        ['query'],
      ),
    'getAllAnimations' : IDL.Func([], [IDL.Vec(AnimationData)], ['query']),
    'getAnimation' : IDL.Func([IDL.Text], [AnimationData], ['query']),
    'getUserPreferences' : IDL.Func([], [UserPreferences], ['query']),
    'isAIGenerated' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'setUserPreferences' : IDL.Func([UserPreferences], [], []),
  });
};

export const init = ({ IDL }) => { return []; };