/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CharacterCustomization {
    accessories: Array<string>;
    characterType: CharacterType;
    color: string;
    props: Array<string>;
    emotionalTone: EmotionalTone;
}
export interface UserPreferences {
    favoriteEnvironments: Array<Environment>;
    preferredEmotionalTone: EmotionalTone;
    preferredColors: Array<string>;
    defaultAudioSettings: AudioSettings;
    favoriteCharacterTypes: Array<CharacterType>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface AudioSettings {
    soundEffectsVolume: bigint;
    includeSoundEffects: boolean;
    narrationVolume: bigint;
    includeNarration: boolean;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AnimationData {
    id: string;
    characterCustomization: CharacterCustomization;
    animationBlob: ExternalBlob;
    backgroundAudioBlob: ExternalBlob;
    createdAt: Time;
    videoBlob: ExternalBlob;
    narrationAudioBlob: ExternalBlob;
    sceneCustomization: SceneCustomization;
    audioSettings: AudioSettings;
    modelBlob: ExternalBlob;
    prompt: string;
    isAIGenerated: boolean;
    textureBlob: ExternalBlob;
}
export interface SceneCustomization {
    backgroundElements: Array<string>;
    environment: Environment;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum CharacterType {
    human = "human",
    animal = "animal",
    fantasyCreature = "fantasyCreature"
}
export enum EmotionalTone {
    sad = "sad",
    surprised = "surprised",
    happy = "happy",
    excited = "excited"
}
export enum Environment {
    city = "city",
    desert = "desert",
    space = "space",
    underwater = "underwater",
    forest = "forest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    downloadVideo(_videoBlob: ExternalBlob): Promise<void>;
    generateAIAnimation(prompt: string, emotionalTone: EmotionalTone, audioSettings: AudioSettings, modelBlob: ExternalBlob, textureBlob: ExternalBlob, animationBlob: ExternalBlob, videoBlob: ExternalBlob, narrationAudioBlob: ExternalBlob, backgroundAudioBlob: ExternalBlob): Promise<AnimationData>;
    getAIGeneratedAnimations(): Promise<Array<AnimationData>>;
    getAllAnimations(): Promise<Array<AnimationData>>;
    getAnimation(id: string): Promise<AnimationData>;
    getUserPreferences(): Promise<UserPreferences>;
    isAIGenerated(animationId: string): Promise<boolean>;
    setUserPreferences(prefs: UserPreferences): Promise<void>;
}
import type { AnimationData as _AnimationData, AudioSettings as _AudioSettings, CharacterCustomization as _CharacterCustomization, CharacterType as _CharacterType, EmotionalTone as _EmotionalTone, Environment as _Environment, ExternalBlob as _ExternalBlob, SceneCustomization as _SceneCustomization, Time as _Time, UserPreferences as _UserPreferences, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async downloadVideo(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.downloadVideo(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.downloadVideo(await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async generateAIAnimation(arg0: string, arg1: EmotionalTone, arg2: AudioSettings, arg3: ExternalBlob, arg4: ExternalBlob, arg5: ExternalBlob, arg6: ExternalBlob, arg7: ExternalBlob, arg8: ExternalBlob): Promise<AnimationData> {
        if (this.processError) {
            try {
                const result = await this.actor.generateAIAnimation(arg0, to_candid_EmotionalTone_n9(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg5), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg6), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg7), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg8));
                return from_candid_AnimationData_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateAIAnimation(arg0, to_candid_EmotionalTone_n9(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg3), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg4), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg5), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg6), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg7), await to_candid_ExternalBlob_n8(this._uploadFile, this._downloadFile, arg8));
            return from_candid_AnimationData_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAIGeneratedAnimations(): Promise<Array<AnimationData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAIGeneratedAnimations();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAIGeneratedAnimations();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAnimations(): Promise<Array<AnimationData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAnimations();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAnimations();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnimation(arg0: string): Promise<AnimationData> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnimation(arg0);
                return from_candid_AnimationData_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnimation(arg0);
            return from_candid_AnimationData_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserPreferences(): Promise<UserPreferences> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserPreferences();
                return from_candid_UserPreferences_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserPreferences();
            return from_candid_UserPreferences_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAIGenerated(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAIGenerated(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAIGenerated(arg0);
            return result;
        }
    }
    async setUserPreferences(arg0: UserPreferences): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserPreferences(to_candid_UserPreferences_n29(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserPreferences(to_candid_UserPreferences_n29(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_AnimationData_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AnimationData): Promise<AnimationData> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_CharacterCustomization_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CharacterCustomization): CharacterCustomization {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_CharacterType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CharacterType): CharacterType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_EmotionalTone_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmotionalTone): EmotionalTone {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Environment_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Environment): Environment {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_SceneCustomization_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SceneCustomization): SceneCustomization {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserPreferences_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPreferences): UserPreferences {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    characterCustomization: _CharacterCustomization;
    animationBlob: _ExternalBlob;
    backgroundAudioBlob: _ExternalBlob;
    createdAt: _Time;
    videoBlob: _ExternalBlob;
    narrationAudioBlob: _ExternalBlob;
    sceneCustomization: _SceneCustomization;
    audioSettings: _AudioSettings;
    modelBlob: _ExternalBlob;
    prompt: string;
    isAIGenerated: boolean;
    textureBlob: _ExternalBlob;
}): Promise<{
    id: string;
    characterCustomization: CharacterCustomization;
    animationBlob: ExternalBlob;
    backgroundAudioBlob: ExternalBlob;
    createdAt: Time;
    videoBlob: ExternalBlob;
    narrationAudioBlob: ExternalBlob;
    sceneCustomization: SceneCustomization;
    audioSettings: AudioSettings;
    modelBlob: ExternalBlob;
    prompt: string;
    isAIGenerated: boolean;
    textureBlob: ExternalBlob;
}> {
    return {
        id: value.id,
        characterCustomization: from_candid_CharacterCustomization_n13(_uploadFile, _downloadFile, value.characterCustomization),
        animationBlob: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.animationBlob),
        backgroundAudioBlob: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.backgroundAudioBlob),
        createdAt: value.createdAt,
        videoBlob: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.videoBlob),
        narrationAudioBlob: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.narrationAudioBlob),
        sceneCustomization: from_candid_SceneCustomization_n20(_uploadFile, _downloadFile, value.sceneCustomization),
        audioSettings: value.audioSettings,
        modelBlob: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.modelBlob),
        prompt: value.prompt,
        isAIGenerated: value.isAIGenerated,
        textureBlob: await from_candid_ExternalBlob_n19(_uploadFile, _downloadFile, value.textureBlob)
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accessories: Array<string>;
    characterType: _CharacterType;
    color: string;
    props: Array<string>;
    emotionalTone: _EmotionalTone;
}): {
    accessories: Array<string>;
    characterType: CharacterType;
    color: string;
    props: Array<string>;
    emotionalTone: EmotionalTone;
} {
    return {
        accessories: value.accessories,
        characterType: from_candid_CharacterType_n15(_uploadFile, _downloadFile, value.characterType),
        color: value.color,
        props: value.props,
        emotionalTone: from_candid_EmotionalTone_n17(_uploadFile, _downloadFile, value.emotionalTone)
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    backgroundElements: Array<string>;
    environment: _Environment;
}): {
    backgroundElements: Array<string>;
    environment: Environment;
} {
    return {
        backgroundElements: value.backgroundElements,
        environment: from_candid_Environment_n22(_uploadFile, _downloadFile, value.environment)
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    favoriteEnvironments: Array<_Environment>;
    preferredEmotionalTone: _EmotionalTone;
    preferredColors: Array<string>;
    defaultAudioSettings: _AudioSettings;
    favoriteCharacterTypes: Array<_CharacterType>;
}): {
    favoriteEnvironments: Array<Environment>;
    preferredEmotionalTone: EmotionalTone;
    preferredColors: Array<string>;
    defaultAudioSettings: AudioSettings;
    favoriteCharacterTypes: Array<CharacterType>;
} {
    return {
        favoriteEnvironments: from_candid_vec_n27(_uploadFile, _downloadFile, value.favoriteEnvironments),
        preferredEmotionalTone: from_candid_EmotionalTone_n17(_uploadFile, _downloadFile, value.preferredEmotionalTone),
        preferredColors: value.preferredColors,
        defaultAudioSettings: value.defaultAudioSettings,
        favoriteCharacterTypes: from_candid_vec_n28(_uploadFile, _downloadFile, value.favoriteCharacterTypes)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    human: null;
} | {
    animal: null;
} | {
    fantasyCreature: null;
}): CharacterType {
    return "human" in value ? CharacterType.human : "animal" in value ? CharacterType.animal : "fantasyCreature" in value ? CharacterType.fantasyCreature : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    surprised: null;
} | {
    happy: null;
} | {
    excited: null;
}): EmotionalTone {
    return "sad" in value ? EmotionalTone.sad : "surprised" in value ? EmotionalTone.surprised : "happy" in value ? EmotionalTone.happy : "excited" in value ? EmotionalTone.excited : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    city: null;
} | {
    desert: null;
} | {
    space: null;
} | {
    underwater: null;
} | {
    forest: null;
}): Environment {
    return "city" in value ? Environment.city : "desert" in value ? Environment.desert : "space" in value ? Environment.space : "underwater" in value ? Environment.underwater : "forest" in value ? Environment.forest : value;
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AnimationData>): Promise<Array<AnimationData>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AnimationData_n11(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Environment>): Array<Environment> {
    return value.map((x)=>from_candid_Environment_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CharacterType>): Array<CharacterType> {
    return value.map((x)=>from_candid_CharacterType_n15(_uploadFile, _downloadFile, x));
}
function to_candid_CharacterType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CharacterType): _CharacterType {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_EmotionalTone_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmotionalTone): _EmotionalTone {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Environment_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Environment): _Environment {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_UserPreferences_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserPreferences): _UserPreferences {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    favoriteEnvironments: Array<Environment>;
    preferredEmotionalTone: EmotionalTone;
    preferredColors: Array<string>;
    defaultAudioSettings: AudioSettings;
    favoriteCharacterTypes: Array<CharacterType>;
}): {
    favoriteEnvironments: Array<_Environment>;
    preferredEmotionalTone: _EmotionalTone;
    preferredColors: Array<string>;
    defaultAudioSettings: _AudioSettings;
    favoriteCharacterTypes: Array<_CharacterType>;
} {
    return {
        favoriteEnvironments: to_candid_vec_n31(_uploadFile, _downloadFile, value.favoriteEnvironments),
        preferredEmotionalTone: to_candid_EmotionalTone_n9(_uploadFile, _downloadFile, value.preferredEmotionalTone),
        preferredColors: value.preferredColors,
        defaultAudioSettings: value.defaultAudioSettings,
        favoriteCharacterTypes: to_candid_vec_n34(_uploadFile, _downloadFile, value.favoriteCharacterTypes)
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmotionalTone): {
    sad: null;
} | {
    surprised: null;
} | {
    happy: null;
} | {
    excited: null;
} {
    return value == EmotionalTone.sad ? {
        sad: null
    } : value == EmotionalTone.surprised ? {
        surprised: null
    } : value == EmotionalTone.happy ? {
        happy: null
    } : value == EmotionalTone.excited ? {
        excited: null
    } : value;
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Environment): {
    city: null;
} | {
    desert: null;
} | {
    space: null;
} | {
    underwater: null;
} | {
    forest: null;
} {
    return value == Environment.city ? {
        city: null
    } : value == Environment.desert ? {
        desert: null
    } : value == Environment.space ? {
        space: null
    } : value == Environment.underwater ? {
        underwater: null
    } : value == Environment.forest ? {
        forest: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CharacterType): {
    human: null;
} | {
    animal: null;
} | {
    fantasyCreature: null;
} {
    return value == CharacterType.human ? {
        human: null
    } : value == CharacterType.animal ? {
        animal: null
    } : value == CharacterType.fantasyCreature ? {
        fantasyCreature: null
    } : value;
}
function to_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Environment>): Array<_Environment> {
    return value.map((x)=>to_candid_Environment_n32(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CharacterType>): Array<_CharacterType> {
    return value.map((x)=>to_candid_CharacterType_n35(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
